---
bundle_repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
    
bundle_packages:
  # # Template
  # - name: nginx
  #   chart_ref: bitnami/nginx
  #   namespace: default      # optional
  #   chart_version: null     # optional
  #   create_namespace: true  # optional
  #   state: present          # optional
  #   wait: fasle             # optional
  #   parameters:             # optional
  #     replicaCount: 2
  #     image:
  #       tag: latest

  # - name: nginx
  #   chart_ref: bitnami/nginx
    - manifest_uri: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/openshift/postgres.yaml
      namespace: "bundle-test"
...